match:
  device:  'cuda:5'  # 'cpu'  # 
  batch_size: 7
  inference_size: [600, 400]
  matcher_weights: '/home/g.nikolaev/petroscope/petroscope/panoramas/weights/loftr_outdoor.ckpt'

align:
  transformation_type: 'affine'  # 'affine' or 'projective'
  confidence_tr: 0.5
  min_inliers: 32
  max_inliers: 40
  min_inlier_rate: 0.0
  reproj_tr: 1.0  # уже устарело, он адаптивный, надо только это Правильно закодить
  n_recenterings: 25
  use_BA: True

compose:
  use_gain_comp: True
  use_graphcut: True
  use_blending: True

gain_comp:
  save_mean_color: True

graphcut:
  coarse_scale: 4
  fine_scale: 16
  lane_width: 200

blending:
  n_levels: 7

dirs:
  tiles_dir: "/home/g.nikolaev/data/tiles"
  cache_dir: "/home/g.nikolaev/data/cache"
  panoramas_dir: "/home/g.nikolaev/data/panoramas"

# dirs:
#   tiles_dir: "/home/g.nikolaev/data/new_tiles"
#   cache_dir: "/home/g.nikolaev/data/new_cache"
#   panoramas_dir: "/home/g.nikolaev/data/new_panoramas"

log:
  detailed_log: True

vizualization:
  draw_inliers: False
  draw_connections: True

load_matches: False
custom_undistortion: True
n_undistortions: 1
# stitching_mode: 'save_matches'
stitching_mode: 'collage'
# adaptive_alignment: True